### PR TITLE
Vector laplacian

### PR DESCRIPTION
**Pull request by IgorBaratta**
- Vector laplacian has same FLOPs as elasticity but moves less data.
- Optimised vector laplacian with reduced number of temporaries.
- Reaches compute bound soon, but we maintain performance.

### CODE REVIEW

**Comment by garth-wells** [comment]
Why is elasticity removed? Doesn’t the need for a symmetric part tell us something extra?

**Comment by IgorBaratta** [comment]
> Why is elasticity removed? Doesn’t the need for a symmetric part tell us something extra?

With the symmetric part we need to send the jacobian for each quadrature point, as it includes `J^{-T} J-1` and `J^{-1} J{-1}`.
Which means that vector laplacian has higher FLOPS/BYTE rate, and it tests a condition that it becomes flop limited sooner.

The only difference between vector laplacian and the previous code is in the geometric transformation part.
The number of tensor contractions remains the same.

**Comment by garth-wells** [comment]
> > Why is elasticity removed? Doesn’t the need for a symmetric part tell us something extra?
> 
> With the symmetric part we need to send the jacobian for each quadrature point, as it includes `J^{-T} J-1` and `J^{-1} J{-1}`. Which means that vector laplacian has higher FLOPS/BYTE rate, and it tests a condition that it becomes flop limited sooner.
> 
> The only difference between vector laplacian and the previous code is in the geometric transformation part. The number of tensor contractions remains the same.

But also need the Jacobian for vector Laplacian.

I don't see much point for to the vector Laplacian - it's just 3x the Laplacian.

**Comment by IgorBaratta** [comment]
> But also need the Jacobian for vector Laplacian.

It only requires the symmetric `{J-T J-1}` component.


> I don't see much point for to the vector Laplacian - it's just 3x the Laplacian.

It reuses the geometric factor, and at single point in time has more data in the caches.

**Comment by garth-wells** [comment]
Superseded by #21

**Pull request closed without merging**
